### ISSUE TITLE
Quasar: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_c') at Proxy.o

### ISSUE THREAD

**Issue by hakuna0829** [Kassaila/vue-json-editor#13]
I've installed this package(vue-json-editor) in the vue quasar project.
Here is the dependency list.

```
"dependencies": {
    "@kassaila/vue-json-editor": "^0.4.0",
    "@quasar/extras": "^1.0.0",
    "core-js": "^3.6.5",
    "lodash": "^4.17.21",
    "quasar": "^2.0.0",
    "vue-i18n": "^9.0.0",
    "vuex": "^4.0.1"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.13.14",
    "@quasar/app": "^3.0.0",
    "eslint": "^7.14.0",
    "eslint-config-standard": "^16.0.2",
    "eslint-plugin-import": "^2.19.1",
    "eslint-plugin-node": "^11.0.0",
    "eslint-plugin-promise": "^5.1.0",
    "eslint-plugin-vue": "^7.0.0",
    "eslint-webpack-plugin": "^2.4.0"
  }
```

But it occurs the TypeError like the title.
Is there anyone who help to solve this issue?
Thanks

**Comment by Kassaila** [comment]
Hello.
This package is written only for `vue ^2.6.12` version usage. 
Sorry but for `vue ^3.*.*` support is not planned.
Thanks for the feedback

**Comment by hakuna0829** [comment]
@Kassaila 
Thanks for your quick message. 
I removed the old one and installed vue3 version again.
https://www.npmjs.com/package/vue3-json-editor
I followed the readme file but still get this console issue.

`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getMode')`

In the view, there is only save button.
![image](https://user-images.githubusercontent.com/50372774/151652786-b8ee8774-c7ca-4e21-8e23-4163a0d4c497.png)

Please guide me.

**Comment by Kassaila** [comment]
@hakuna0829 
Sorry, i can't help you. I am not using `vue3-json-editor`.
I think you'd better ask the developers of [vue3-json-editor](https://github.com/joaomede/vue3-json-editor/issues) package.

**Comment by hakuna0829** [comment]
@Kassaila Thanks for your advice.
