### ISSUE TITLE
How to customize slot to pass props variable ?

### ISSUE THREAD

**Issue by tptspe** [Kassaila/vue-json-editor#15]
I want to customize slot to pass variable or function to slot template.
For example, there is icon-add slot and its code looks like inside item-view.vue.
And, I want to pass one string variable called `serialKey` .

`<template >              
  <slot name="icon-add" :serialKey="s_serialKey" > </slot>
</template>`
...

How to get it from here?

`<button
      v-if="!itemForm"
      type="button"
      class="json-editor__btn json-editor__btn_icon"
      @click="toggleForm"
    >
  <slot name="icon-add">
    <span class="btn-icon btn-icon_add" title="Add">+</span>
   </slot>
</button>`

Is this possible and what is the solution?
Thanks.

**Comment by Kassaila** [comment]
Example for using slots:

```vue
<json-editor
:data-input="dataInput"
@data-output="(data) => (dataOutput = data)"
 >
  <template #icon-add>
    <span class="btn-icon btn-icon_add" title="Add">+</span>
  </template>
</json-editor>
```

If you want customize `json-editor` source code, particularly slots.
Please read official documentation how work with [scoped slots](https://vuejs.org/guide/components/slots.html#scoped-slots)
